### ISSUE TITLE
Examples are not Copy&Paste friendly

### ISSUE THREAD

**Issue by Orasund** [Orasund/elm-ui-widgets#14]
> I am having some difficulty following the docs and example code.
>
>The examples define the view function such as:
>`view : (Msg -> msg) -> Style style msg -> Model -> Element msg`
>…
>`view = view identity materialStyle >> Element.layout []`
>
>But I am used to view functions more like this:
>`view : Model -> { title : String, content : List (Element Msg) }`
>
>It feels like I must be missing something pretty basic here, but how are these other params getting passed into this function? I >guess I thought the runtime would always just pass the model in to the view function? Can’t seem to find any references describing a view function with a type signature like this either.
>
>Would love to get some clarification on how to use the package and hope this is not a silly question where I am overlooking something pretty obvious.

From a DM via Discourse

**Comment by Orasund** [comment]
My Answer:

>Hi there, you are not the first having troubles with the examples. But I'm not quite sure how I fix that. The examples where meant >for testing out the package before using it. Not for copy & pasting.
>
>Here is an example that maybe fits more your needs.
>```
>style = materialStyle
>
>view : Model -> { title : String, content : List (Element Msg) }
>view (IsButtonEnabled isbuttonEnabled) =
>  { title = "Button Example"
>  , content = 
>    [ Widget.button style.primaryButton
>        { text = "disable me"
>        , icon =
>            FeatherIcons.slash
>                |> FeatherIcons.withSize 16
>                |> FeatherIcons.toHtml []
>                |> Element.html
>                |> Element.el []
>        , onPress =
>            if isButtonEnabled then
>                ChangedButtonStatus False
>                    |> Just
>
>            else
>                Nothing
>        }
>    , Widget.iconButton style.button
>        { text = "reset"
>        , icon =
>            FeatherIcons.repeat
>                |> FeatherIcons.withSize 16
>                |> FeatherIcons.toHtml []
>                |> Element.html
>                |> Element.el []
>        , onPress =
>            ChangedButtonStatus True
>                |> Just
>        }
>    ]
>  }
>```

**Comment by GaryBozek** [comment]
As a relative n00b myself, I appreciated having the Ellie code.  The package developers write some great code, but they forget that others may not be at their level of knowledge/experience.  In my learning journey, I have noticed that some package developers make the assumption that you can figure out how to use the package just from the documentation.  Kudos to you for including the Ellie code as a jumping off point for those of us who aren't quite there yet.

I also struggled a bit to implement the Button example into my own code base (specifically:  , view = view identity materialStyle **_>> Element.layout []_**).  I guess I have learned enough to understand what had to change in my code to make it work.

The [obvious/simple/easy] fix for this Issue is to publish the repository code for the demo (https://orasund.github.io/elm-ui-widgets/2.0.0/).  I'm sure it would help me understand how to implement the widgets.

Thank you for developing the package!!!

**Comment by Orasund** [comment]
source code is [here](https://github.com/Orasund/elm-ui-widgets/tree/master/example/src).

The interesting file is [Stateless.elm](https://github.com/Orasund/elm-ui-widgets/blob/master/example/src/Stateless.elm), where I include the submodule of the corresponding example.

**Comment by Orasund** [comment]
I believe the source code is enough for people to figure out the rest. I have not the intent to change anything regarding the examples.
