### ISSUE TITLE
width selected button

### ISSUE THREAD

**Issue by niqt** [Orasund/elm-ui-widgets#27]
Hi,
i see that the selectedbutton show correctly only when the string has size 1, is exsiting a way to scale on the string size?

**Comment by Orasund** [comment]
I believe you mean the select button from the Material theme? This is intentional (by the [Material design specification](https://material.io/components/buttons#toggle-button)).

If you want to change that behaviour, just adjust `Material.toggleButton` to your liking:

https://ellie-app.com/c4xGDjdQkhfa1

If you have any further questions, just ask ;)

**Comment by niqt** [comment]
Hi, i got it! Nice
