### ISSUE TITLE
Expose UIExplorer in the elm-ui package

### ISSUE THREAD

**Issue by cdevienne** [Orasund/elm-ui-widgets#76]
I think the UIExplorer tooling is worth being exposed so app creators can extend it with their own project-specific components.

The current 'pages' function in explorer/src/Main.elm should be exposed too, possibly as a page group (I think the UiExplorer we used as a base is able to do that).

We could also expose in its own package (elm-ui-explorer sounds nice), which could be better but the dependency on elm-ui-widget may be cumbersome when working on elm-ui-widgets itself.

**Comment by Orasund** [comment]
It's definitely something I'd like to see, but I'm not to keen on maintaining another package. If you like to do it, that would be great.

I'm not sure if the code in this current state is easy to expose into its own package. There are a lot of code snippets that I've commented out because I wasn't sure if it is necessary or not (like the possibility to have sub-pages).

**Comment by cdevienne** [comment]
fair enough, I'll give it some thinking.
If I get a solid independent package, would you consider dropping the explorer from elm-ui-widgets ?

**Comment by Orasund** [comment]
YES! I would drop it in an instant.
