### ISSUE TITLE
Handling Return key press in textInput

### ISSUE THREAD

**Issue by bilus** [Orasund/elm-ui-widgets#82]
Is there a way to do it without forking/creating a PR to the library? :)

My use case is two fold:
- Login form
- Search in AppBar.

Thanks!

**Comment by Orasund** [comment]
I guess you mean handling the enter key?

The way to handle this is to use the [Html.Events.on](https://package.elm-lang.org/packages/elm/html/latest/Html-Events#on) event. Here is an [Ellie](https://ellie-app.com/5X6jBKtxzdpa1) that might help.

I'm closing the issue, as the problem is not specific to this package.
